#
#[extension]
#
#open-cmd="%programfiles%\\Microsoft VS Code\\Code.exe" 
#open-cmdline=%file%
#open-atline-cmd="%programfiles%\\Microsoft VS Code\\Code.exe" 
#open-atline-cmdline="--goto \"%file%\":%line%:1"
#
#[extension "cs,cpp,h,rc,c,vb,xaml,xml,xslt,sql"]
#
#open-cmd="%programfiles%\\Microsoft Visual Studio\\2022\\Preview\\Common7\\IDE\\devenv.exe"
#open-cmdline="/edit \"%file%\""
#open-atline-cmd="%programfiles%\\Microsoft Visual Studio\\2022\\Preview\\Common7\\IDE\\devenv.exe"
#open-atline-cmdline="/edit \"%file%\" /command \"edit.goto %line%\""
#
#[compare]
#cmd="%programfiles%\\Meld\\Meld.exe"
#cmdline="\"%file1%\" \"%file2%\""
editors:
 - ext: [cs,cpp,h,rc,c,xaml,xml,xslt,sql]
   open-command: "%programfiles%\\Microsoft Visual Studio\\2022\\Preview\\Common7\\IDE\\devenv.exe"
   cmd-line: "/edit \"%file%\""
   cmd-line-at: "/edit \"%file%\" /command \"edit.goto %line%\""

default-editor:
 ext: #default, match other extensions
 open-command: "%programfiles%\\Microsoft VS Code\\Code.exe"
 cmd-line: "\"%file%\""
 cmd-line-at: "--goto \"%file%\":%line%:1"


compare:
  open-command: "%programfiles%\\Meld\\Meld.exe"
  cmd-line: "\"%file1%\" \"%file2%\""



 