#
#[extension]
#
#open-cmd="%programfiles%\\Microsoft VS Code\\Code.exe" 
#open-cmdline=%file%
#open-atline-cmd="%programfiles%\\Microsoft VS Code\\Code.exe" 
#open-atline-cmdline="--goto \"%file%\":%line%:1"
#
#[extension "cs,cpp,h,rc,c,vb,xaml,xml,xslt,sql"]
#
#open-cmd="%programfiles%\\Microsoft Visual Studio\\2022\\Preview\\Common7\\IDE\\devenv.exe"
#open-cmdline="/edit \"%file%\""
#open-atline-cmd="%programfiles%\\Microsoft Visual Studio\\2022\\Preview\\Common7\\IDE\\devenv.exe"
#open-atline-cmdline="/edit \"%file%\" /command \"edit.goto %line%\""
#
#[compare]
#cmd="%programfiles%\\Meld\\Meld.exe"
#cmdline="\"%file1%\" \"%file2%\""
config:
 - editor:
   ext:
    - cs
    - cpp
    - h
    - rc
    - c
    - xaml
    - xml
    - xslt
    - sql
   open-command: "%programfiles%\\Microsoft Visual Studio\\2022\\Preview\\Common7\\IDE\\devenv.exe"
   cmdline: "/edit \"%file%\""
   atline-cmdline: "/edit \"%file%\" /command \"edit.goto %line%\""
 - editor:
   ext: #default, match other extensions
   open-command: "%programfiles%\\Microsoft VS Code\\Code.exe"
   cmdline: "\"%file%\""
   atline-cmdline: "--goto \"%file%\":%line%:1"
compare:
 open-command: "%programfiles%\\Meld\\Meld.exe"
 cmdline: "\"%file1%\" \"%file2%\""



 